[package]
categories.workspace  = true
description.workspace = true
edition.workspace     = true
keywords.workspace    = true
license.workspace     = true
name                  = "testing-framework-runner-k8s"
readme.workspace      = true
repository.workspace  = true
version               = "0.1.0"

[lints]
workspace = true

[dependencies]
anyhow                 = "1"
async-trait            = { workspace = true }
k8s-openapi            = { version = "0.20", features = ["latest"] }
kube                   = { version = "0.87", default-features = false, features = ["client", "runtime", "rustls-tls"] }
reqwest                = { workspace = true, features = ["json"] }
serde                  = { version = "1", features = ["derive"] }
serde_yaml             = { workspace = true }
tempfile               = { workspace = true }
testing-framework-core = { path = "../../core" }
thiserror              = { workspace = true }
tokio                  = { workspace = true, features = ["macros", "net", "process", "rt-multi-thread", "sync", "time"] }
tracing                = { workspace = true }
url                    = { version = "2" }
uuid                   = { version = "1", features = ["v4"] }
