[package]
edition = { workspace = true }
license = { workspace = true }
name    = "nomos-sdp"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
async-trait   = "0.1"
ed25519-dalek = { default-features = false, version = "2.2.0" }
futures       = { default-features = false, version = "0.3" }
nomos-core    = { workspace = true }
overwatch     = { workspace = true }
serde         = { default-features = false, features = ["derive"], version = "1.0" }
thiserror     = { workspace = true }
tokio         = { default-features = false, version = "1" }
tokio-stream  = { default-features = false, version = "0.1" }
tracing       = { workspace = true }
tx-service    = { workspace = true }
