[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "zksign"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[dependencies]
ark-ff            = { default-features = false, version = "0.4" }
circuits-prover   = { workspace = true }
circuits-utils    = { workspace = true }
generic-array     = "1.2.0"
groth16           = { features = ["deser"], workspace = true }
num-bigint        = { version = "0.4", default-features = false }
poseidon2         = { workspace = true }
serde             = { features = ["derive"], version = "1.0" }
serde_json        = { workspace = true }
thiserror         = { workspace = true }
tracing           = { workspace = true }
witness-generator = { workspace = true }
zeroize           = { workspace = true }

[dev-dependencies]
num-bigint = "0.4"
poseidon2  = { workspace = true }
rand       = "0.8"

[build-dependencies]
circuits-utils = { workspace = true }

[lints]
workspace = true
