[package]
categories.workspace  = true
description.workspace = true
edition.workspace     = true
keywords.workspace    = true
license.workspace     = true
name                  = "testing-framework-runner-compose"
readme.workspace      = true
repository.workspace  = true
version               = "0.1.0"

[lints]
workspace = true

[dependencies]
anyhow                 = "1"
async-trait            = { workspace = true }
axum                   = { version = "0.7", default-features = false, features = ["http1", "json", "tokio"] }
cfgsync                = { workspace = true }
reqwest                = { workspace = true, features = ["json"] }
serde                  = { workspace = true, features = ["derive"] }
tempfile               = { workspace = true }
tera                   = "1.19"
testing-framework-core = { path = "../../core" }
thiserror              = { workspace = true }
tokio                  = { workspace = true, features = ["macros", "net", "process", "rt-multi-thread", "sync", "time"] }
tracing                = { workspace = true }
url                    = { version = "2" }
uuid                   = { version = "1", features = ["v4"] }

[dev-dependencies]
groth16               = { workspace = true }
nomos-core            = { workspace = true }
nomos-ledger          = { workspace = true }
nomos-tracing-service = { workspace = true }
zksign                = { workspace = true }
