[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "broadcast-service"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[lints]
workspace = true

[dependencies]
async-trait  = "0.1"
derivative   = { default-features = false, version = "2" }
futures      = { default-features = false, version = "0.3" }
nomos-core   = { workspace = true }
overwatch    = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
tokio        = { default-features = false, version = "1" }
tokio-stream = { default-features = false, version = "0.1" }
tracing      = { workspace = true }
