[package]
edition = { workspace = true }
license = { workspace = true }
name    = "chain-network"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
async-trait        = "0.1"
chain-common       = { workspace = true }
chain-service      = { workspace = true }
cryptarchia-engine = { features = ["serde"], workspace = true }
cryptarchia-sync   = { workspace = true }
futures            = { default-features = false, version = "0.3" }
nomos-core         = { workspace = true }
nomos-da-sampling  = { workspace = true }
nomos-ledger       = { features = ["serde"], workspace = true }
nomos-network      = { workspace = true }
nomos-time         = { workspace = true }
overwatch          = { workspace = true }
rand               = { default-features = false, version = "0.8" }
serde              = { default-features = false, version = "1" }
serde_with         = { workspace = true }
services-utils     = { workspace = true }
thiserror          = "1.0"
tokio              = { default-features = false, version = "1" }
tokio-stream       = { default-features = false, version = "0.1" }
tracing            = { workspace = true }
tracing-futures    = { default-features = false, version = "0.2" }
tx-service         = { workspace = true }

[dev-dependencies]
nomos-core    = { features = ["mock"], workspace = true }
nomos-network = { features = ["mock"], workspace = true }

[features]
default      = []
libp2p       = ["nomos-network/libp2p"]
pol-dev-mode = ["nomos-core/pol-dev-mode"]
